load("@rules_cuda//cuda:defs.bzl", "cuda_library", "cuda_test")

cuda_library(
    name = "buffer",
    srcs = ["memory/buffer.cu"],
    hdrs = ["memory/buffer.h"],
    deps = [
        "//common:cuda_stream",
        "//common:types",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "buffer_pool",
    srcs = ["memory/buffer_pool.cc"],
    hdrs = ["memory/buffer_pool.h"],
    deps = [
        ":buffer",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "core",
    srcs = [
        "core/point_cloud.cc",
        "core/point_cloud_buffer.cc",
    ],
    hdrs = [
        "core/point_cloud.h",
        "core/point_cloud_buffer.h",
        "core/rigid_transform.h",
    ],
    deps = [
        ":buffer",
        "//common:cuda_stream",
        "//common:types",
        "@eigen//:eigen",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "range_image_api",
    hdrs = [
        "range_image/range_image.h",
        "range_image/range_image_builder.h",
    ],
    deps = [
        ":buffer",
        ":core",
        "//common:cuda_stream",
    ],
    visibility = ["//visibility:public"],
)

cuda_library(
    name = "range_image",
    srcs = ["range_image/range_image_builder.cu"],
    deps = [
        ":range_image_api",
    ],
    visibility = ["//visibility:public"],
)

cuda_library(
    name = "filter",
    srcs = [
        "filter/crop_box_filter.cu",
        "filter/decimation_filter.cu",
        "filter/internal/device_filter_utils.cuh",
    ],
    hdrs = [
        "filter/crop_box_filter.h",
        "filter/decimation_filter.h",
    ],
    deps = [
        ":buffer",
        ":core",
        "//common:cuda_stream",
        "//common:types",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "pointcloud",
    deps = [
        ":buffer",
        ":buffer_pool",
        ":core",
        ":filter",
        ":range_image",
        ":range_image_api",
        "//common:cuda_stream",
        "//common:types",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "point_cloud_view_test",
    srcs = ["core/point_cloud_view_test.cc"],
    deps = [
        ":core",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "point_cloud_buffer_test",
    srcs = ["core/point_cloud_buffer_test.cc"],
    deps = [
        ":core",
        "@googletest//:gtest_main",
    ],
)

cuda_test(
    name = "range_image_test",
    srcs = ["range_image/range_image_test.cc"],
    deps = [
        ":pointcloud",
        "@googletest//:gtest_main",
    ],
)

cuda_test(
    name = "decimation_filter_test",
    srcs = ["filter/decimation_filter_test.cc"],
    deps = [
        ":pointcloud",
        "@googletest//:gtest_main",
    ],
)

cuda_test(
    name = "crop_box_filter_test",
    srcs = ["filter/crop_box_filter_test.cc"],
    deps = [
        ":pointcloud",
        "@googletest//:gtest_main",
    ],
)
