load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cc_library(
    name = "image_stitcher",
    srcs = ["image_stitcher.cc"],
    hdrs = ["image_stitcher.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "ipm_transformer",
    srcs = ["ipm_transformer.cc"],
    hdrs = ["ipm_transformer.h"],
    visibility = ["//visibility:public"],
)

cuda_library(
    name = "view_transformer",
    srcs = ["view_transformer.cu"],
    hdrs = ["view_transformer.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "image",
    deps = [
        ":image_stitcher",
        ":ipm_transformer",
        ":view_transformer",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "image_stitcher_test",
    srcs = ["image_stitcher_test.cc"],
    deps = [
        ":image_stitcher",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "ipm_transformer_test",
    srcs = ["ipm_transformer_test.cc"],
    deps = [
        ":ipm_transformer",
        "@googletest//:gtest_main",
    ],
)
